module.exports = {
  tabWidth: 2,
  printWidth: 100,
  semi: true,
  useTabs: false,
  singleQuote: true,
  insertPragma: false,
  requirePragma: false,
  bracketSpacing: true,
  jsxSingleQuote: false,
  jsxBracketSameLine: false,
  endOfLine: "auto",
  arrowParens: 'avoid',
  trailingComma: 'es5',
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  htmlWhitespaceSensitivity: 'css',
};
